"use client";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight } from "lucide-react";
import Image from "next/image";
import { useEffect, useState } from "react";
const slides = ["/images/hero-1.webp", "/images/hero-2.webp", "/images/hero-3.webp", "/images/hero-4.webp", "/images/hero-5.webp"];
export function Hero() { const [current, setCurrent] = useState(0); const go = (amount:number) => setCurrent(p => (p + amount + slides.length) % slides.length); useEffect(() => { const id = window.setInterval(() => go(1), 5600); return () => window.clearInterval(id); }, []); return <section id="inicio" className="relative isolate min-h-[720px] overflow-hidden bg-[#0B1F3A] text-white md:min-h-screen">
  <AnimatePresence mode="sync"><motion.div key={current} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.8}} className="absolute inset-0"><Image src={slides[current]} alt="Servicio Premium Work" fill priority={current === 0} sizes="(max-width: 768px) 100vh, 100vw"
 className="object-cover object-right object-top"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(11,31,58,.12)_0%,rgba(11,31,58,.28)_45%,rgba(11,31,58,.91)_100%)]" /><div className="absolute inset-y-0 left-0 w-2/3 bg-[linear-gradient(90deg,rgba(11,31,58,.64),transparent)]"/></motion.div></AnimatePresence>
  <div className="relative mx-auto flex min-h-[720px] max-w-[1600px] items-end px-5 pb-24 pt-32 md:min-h-screen md:px-8 md:pb-28"><motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="max-w-5xl"><p className="mb-5 text-xs font-bold uppercase tracking-[.18em] text-[#e5c65a]">Hospitality · eventos · excelencia </p><h1 className="display max-w-4xl text-5xl leading-[.94] sm:text-7xl lg:text-8xl">¿ Servicio perfecto ?<br/><em className="font-normal text-[#e5c65a]">Equipo correcto.</em></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/80"> Seleccionado, formado y supervisado a la medida de su marca </p><a href="#contacto" className="mt-8 inline-flex rounded-sm bg-[#C9A227] px-6 py-3.5 text-sm font-bold text-[#0B1F3A] transition hover:scale-[1.03] active:scale-[.98]">EMPRESAS / Solicitar servicio</a></motion.div></div>
  <div className="absolute bottom-8 left-5 right-5 flex items-end gap-6 md:left-8 md:right-8"><div className="flex flex-1 gap-2">{slides.map((_, i) => <button aria-label={`Ver imagen ${i + 1}`} onClick={() => setCurrent(i)} className="h-1 flex-1 bg-white/35" key={i}><span className={`block h-full bg-white transition-all ${i === current ? "w-full" : "w-0"}`} /></button>)}</div><div className="flex border border-white/50"><button aria-label="Imagen anterior" onClick={() => go(-1)} className="p-3 hover:bg-white/15"><ArrowLeft size={18}/></button><button aria-label="Imagen siguiente" onClick={() => go(1)} className="border-l border-white/50 p-3 hover:bg-white/15"><ArrowRight size={18}/></button></div></div>
 </section>; }
